# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 00:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peptideinfo',
            old_name='sequence',
            new_name='peptide',
        ),
    ]
