# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0004_reference_doi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='author',
            new_name='authors',
        ),
        migrations.AddField(
            model_name='reference',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
