# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 01:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0006_auto_20160712_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='citation',
        ),
    ]
