# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0008_proteininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteininfo',
            name='header',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
