# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0013_function_secondary_func'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='secondary_func',
            new_name='detail',
        ),
    ]
