# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0014_auto_20161206_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='peptide.Function'),
        ),
    ]
