# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-27 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0015_auto_20170127_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='pep',
            new_name='func',
        ),
    ]
