# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0016_auto_20170127_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peptideinfo',
            name='aa_after_peptide',
        ),
    ]
