# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0017_remove_peptideinfo_aa_after_peptide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peptideinfo',
            name='species',
        ),
    ]
