# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-11 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0018_remove_peptideinfo_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptideinfo',
            name='category',
            field=models.CharField(default='dairy', max_length=50),
            preserve_default=False,
        ),
    ]
