# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-15 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0019_peptideinfo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='function',
            old_name='detail',
            new_name='secondary_func',
        ),
    ]
