# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-07 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0023_peptideinfo_time_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(max_length=30)),
                ('peptide', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=400)),
                ('secondary_function', models.CharField(default=b'', max_length=400)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('abstract', models.CharField(max_length=1000)),
                ('doi', models.CharField(max_length=100)),
                ('time_submitted', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='peptideinfo',
            name='time_submitted',
        ),
        migrations.AlterField(
            model_name='reference',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
