# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-14 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0024_auto_20170407_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='start',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='stop',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
