# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-02 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0025_auto_20170413_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peptideinfo',
            name='start',
        ),
        migrations.RemoveField(
            model_name='peptideinfo',
            name='stop',
        ),
        migrations.AddField(
            model_name='peptideinfo',
            name='intervals',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
