# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-09-01 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0030_auto_20170526_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='ptm',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='submission',
            name='ptm',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
