# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2023-06-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0032_auto_20180301_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='ic50',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='submission',
            name='ic50',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
