# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2023-06-29 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0034_auto_20230629_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ic50',
            field=models.CharField(max_length=50),
        ),
    ]
