# Generated by Django 4.2.3 on 2023-07-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0037_alter_counter_id_alter_function_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='ic50',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='ic50',
        ),
    ]
