# Generated by Django 4.2.3 on 2023-08-21 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0038_remove_reference_ic50_remove_submission_ic50'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peptideinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='category',
        ),
    ]
