# Generated by Django 4.2.3 on 2023-08-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0042_alter_proteininfo_seq_alter_proteinvariant_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininfo',
            name='species',
            field=models.CharField(max_length=150),
        ),
    ]
