# Generated by Django 4.2.4 on 2023-09-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0044_alter_peptideinfo_peptide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='secondary_func',
            new_name='additional_details',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='secondary_function',
            new_name='additional_details',
        ),
        migrations.AddField(
            model_name='reference',
            name='ic50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='inhibited_microorganisms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reference',
            name='inhibition_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='ic50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='inhibited_microorganisms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='inhibition_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
