# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeptideInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=300)),
                ('protein', models.CharField(max_length=1000)),
                ('species', models.CharField(max_length=50)),
                ('function', models.CharField(max_length=200)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('length', models.IntegerField()),
                ('aa_after_peptide', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=300)),
                ('abstract', models.CharField(max_length=1000)),
                ('citation', models.CharField(max_length=1000)),
                ('pep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='peptide.PeptideInfo')),
            ],
        ),
    ]
