# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0002_auto_20160630_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='peptideinfo',
            name='function',
        ),
        migrations.AddField(
            model_name='function',
            name='pep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='peptide.PeptideInfo'),
        ),
    ]
