# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0003_auto_20160701_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='doi',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
