# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-03 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0007_remove_reference_citation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('seq', models.CharField(max_length=1000)),
                ('func', models.CharField(max_length=500)),
                ('species', models.CharField(max_length=70)),
            ],
        ),
    ]
