# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0009_proteininfo_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptideinfo',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proteins', to='peptide.ProteinInfo'),
        ),
    ]
