# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0010_auto_20161205_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteininfo',
            old_name='func',
            new_name='desc',
        ),
    ]
