# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0011_auto_20161205_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininfo',
            name='seq',
            field=models.CharField(max_length=5000),
        ),
    ]
