# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0012_auto_20161205_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='secondary_func',
            field=models.CharField(default=b'', max_length=400),
        ),
    ]
