# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0021_auto_20170316_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='secondary_func',
        ),
        migrations.AddField(
            model_name='function',
            name='secondary_func',
            field=models.CharField(default=b'', max_length=400),
        ),
    ]
