# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 00:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
#from datetime import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0022_auto_20170316_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptideinfo',
            name='time_submitted',
            #field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 0, 36, 31, 247362, tzinfo=timezone.utc)),
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 29, 0, 36, 31, 247362, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
