# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0027_auto_20170502_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('access_time', models.DateTimeField()),
            ],
        ),
    ]
