# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-11 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0028_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='page',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
