# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-01 09:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0031_auto_20170901_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.CharField(max_length=5000)),
                ('pvid', models.CharField(max_length=30)),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orig_proteins', to='peptide.ProteinInfo')),
            ],
        ),
        migrations.AddField(
            model_name='peptideinfo',
            name='protein_variants',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='peptideinfo',
            name='time_approved',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 9, 26, 29, 411842, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='protein_variants',
            field=models.CharField(default=b'', max_length=30),
        ),
    ]
