# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2023-06-29 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0033_auto_20230629_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='ic50',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ic50',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
