# Generated by Django 4.2.3 on 2023-07-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0036_auto_20230629_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='function',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peptideinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='peptideinfo',
            name='protein_variants',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='proteininfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proteinvariant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='ptm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='reference',
            name='secondary_func',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='protein_variants',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ptm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='submission',
            name='secondary_function',
            field=models.CharField(default='', max_length=400),
        ),
    ]
