# Generated by Django 4.2.3 on 2023-08-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0039_remove_peptideinfo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininfo',
            name='seq',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='proteinvariant',
            name='seq',
            field=models.CharField(max_length=10000),
        ),
    ]
