# Generated by Django 4.2.3 on 2023-08-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0040_alter_proteininfo_seq_alter_proteinvariant_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininfo',
            name='seq',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='proteinvariant',
            name='seq',
            field=models.CharField(max_length=5000),
        ),
    ]
