# Generated by Django 4.2.3 on 2023-08-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0043_alter_proteininfo_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptideinfo',
            name='peptide',
            field=models.CharField(max_length=500),
        ),
    ]
