# Generated by Django 4.2.4 on 2023-09-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0045_rename_secondary_func_reference_additional_details_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='function',
            unique_together={('pep', 'function')},
        ),
    ]
