# Generated by Django 5.1.3 on 2025-07-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0046_alter_function_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'GitHub Actions',
                'verbose_name_plural': 'GitHub Actions',
                'managed': False,
            },
        ),
    ]
