# Generated by Django 5.1.3 on 2026-08-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptide', '0047_githubactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peptideinfo',
            name='peptide',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='proteininfo',
            name='pid',
            field=models.CharField(db_index=True, max_length=30),
        ),
    ]
